### ISSUE TITLE
Trouble while importing

### ISSUE THREAD

**Issue by thekofimensah** [canvas-medical/kibana-html-formatter#1]
I'm not exactly sure what your plugin does, but I'm hoping it allows me to input html/javascript into my dashboard on Kibana.

Either way, when I try and download it, this is the error I get:

```
Attempting to transfer from https://github.com/canvas-medical/kibana-html-formatter/releases/download/v5.2.2/html-formatter-5.2.2.zip
Transferring 21343027 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Error: EMFILE: too many open files, open '/usr/share/kibana/plugins/.plugin.installing/node_modules/less/test/less/sourcemaps-empty/empty.less'
Plugin installation was unsuccessful due to error "Error extracting plugin archive"
Unhandled rejection Error: EMFILE: too many open files, open '/usr/share/kibana/optimize/.babelcache.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at process.save (/usr/share/kibana/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:146:15)
    at /usr/share/kibana/src/cli_plugin/install/install.js:59:13
    at undefined.throw (native)
    at step (/usr/share/kibana/src/cli_plugin/install/install.js:9:287)
    at tryCatcher (/usr/share/kibana/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/usr/share/kibana/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/usr/share/kibana/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/kibana/node_modules/bluebird/js/main/async.js:133:10)
```

**Comment by beaugunderson** [comment]
hey @seanziee, the 5.2.2 release version is broken right now... as is the plugin itself; currently trying to work with Elastic to figure out what's up with plugins in 5.x

the purpose of the plugin is to allow HTML display of fields in the Discover view so it may not do what you want :/
